// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgk-v7tqPxzQadKTxH9cqfWKcItKIab90',
    appId: '1:305690500747:web:648cd319cbf8cf94c17e8e',
    messagingSenderId: '305690500747',
    projectId: 'informateach-75811',
    authDomain: 'informateach-75811.firebaseapp.com',
    storageBucket: 'informateach-75811.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWGPpu_xGXpo3rsPd2161sK6CVcSoTyfc',
    appId: '1:305690500747:android:e556b7a8a37b2be6c17e8e',
    messagingSenderId: '305690500747',
    projectId: 'informateach-75811',
    storageBucket: 'informateach-75811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNRyGFnoIsz49iyVqxwIpYGjRnOXG5dU',
    appId: '1:305690500747:ios:42079140dfbc932cc17e8e',
    messagingSenderId: '305690500747',
    projectId: 'informateach-75811',
    storageBucket: 'informateach-75811.appspot.com',
    iosBundleId: 'com.example.informateach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjNRyGFnoIsz49iyVqxwIpYGjRnOXG5dU',
    appId: '1:305690500747:ios:c824e74ec303c7bcc17e8e',
    messagingSenderId: '305690500747',
    projectId: 'informateach-75811',
    storageBucket: 'informateach-75811.appspot.com',
    iosBundleId: 'com.example.informateach.RunnerTests',
  );
}
